chore(actions): check signature

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -31,12 +31,28 @@ jobs:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/java
       - uses: gradle/actions/wrapper-validation@v4
-      - name: check dependency graph
+      - uses: actions/dependency-review-action@v4
+      - name: check dependency graph(checksum)
         shell: bash
         run: |
           ./gradlew --write-verification-metadata sha256 resolveAllDependencies --dry-run --scan
-      - uses: actions/dependency-review-action@v4
-      - name: check verification-metadata.xml diff
+      - name: check verification-metadata.xml diff(checksum)
+        shell: bash
+        run: |
+          if [ -n "$(diff gradle/verification-metadata.xml gradle/verification-metadata.dryrun.xml)" ]; then
+            echo "::error::verification-metadata.xml must have updates. Please run check and commit the changes";
+            echo "::group::diff";
+            echo "$(diff gradle/verification-metadata.xml gradle/verification-metadata.dryrun.xml)";
+            echo "::endgroup::";
+            exit 1
+          else
+            echo "::notice::verification-metadata.xml is up-to-date";
+          fi
+      - name: check dependency graph(signature)
+        shell: bash
+        run: |
+          ./gradlew --write-verification-metadata pgp,sha256 resolveAllDependencies --dry-run --scan
+      - name: check verification-metadata.xml diff(signature)
         shell: bash
         run: |
           if [ -n "$(diff gradle/verification-metadata.xml gradle/verification-metadata.dryrun.xml)" ]; then
